In [21]:
import numpy as np
np.array([1,2,3,4,5], dtype='int')
#unlike python list, np array is 1 data type only. and can be multidimensional

#creating arrays
np.random.seed(0)
x = np.zeros(10)
print(x)
x = np.ones((2,3),dtype='float')
print(x)
x = np.full((2,3),'a')
print(x)

x = np.arange(0,10,2)
print(x)

x= np.linspace(0, 1, 5)
print(x)

x= np.random.random((3, 3))
print(x)

x= np.random.normal(0, 1, (3, 3))
print(x)

x= np.random.randint(0, 10, (3, 3))
print(x)

x= np.eye(3)
print(x)

x= np.empty(3)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[['a' 'a' 'a']
 ['a' 'a' 'a']]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
[[ 1.26611853 -0.50587654  2.54520078]
 [ 1.08081191  0.48431215  0.57914048]
 [-0.18158257  1.41020463 -0.37447169]]
[[0 1 9]
 [9 0 4]
 [7 3 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [24]:
#numpy array attributes
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [28]:
#array indexing
print(x1)
print(x1[2])
print(x2)
print(x2[1,-1])

[3 4 5 3 3 7]
5
[[9 9 9 7]
 [3 2 3 9]
 [7 7 5 1]]
9


In [43]:
#array slicing
#format is x[start:stop:step]
print(x1)
print(x1[:2])
print(x1[0:3])
print(x1[2:])
print(x1[0:5:2])

#to reverse the array, step value is negative.
#start and stop values are swapped

print(x1[::-1])
print(x1[5:1:-2])

[3 4 5 3 3 7]
[3 4]
[3 4 5]
[5 3 3 7]
[3 5 3]
[7 3 3 5 4 3]
[7 3]


In [48]:
#array slicing 
print(x2)
print(x2[:2, :3])
print(x2[:2,::2])
print(x2[::-1,::-1])

[[9 9 9 7]
 [3 2 3 9]
 [7 7 5 1]]
[[9 9 9]
 [3 2 3]]
[[9 9]
 [3 3]]
[[1 5 7 7]
 [9 3 2 3]
 [7 9 9 9]]


In [49]:
#accessing array rows and columns
#these slices are only views

print(x2[:, 0])  # first column of x2

print(x2[0, :])  # first row of x2

print(x2[0])  # equivalent to x2[0, :]


[9 3 7]
[9 9 9 7]
[9 9 9 7]


In [53]:
#no copy subarray
x2_sub = x2[:2,:2]
print(x2_sub)
x2_sub[0,0] = 99
print(x2) #original array also changes

#to create a copy of array slicing
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0, 0] = 5
print(x2_sub_copy)
print(x2) #original array does not change


[[99  9]
 [ 3  2]]
[[99  9  9  7]
 [ 3  2  3  9]
 [ 7  7  5  1]]
[[99  9]
 [ 3  2]]
[[5 9]
 [3 2]]
[[99  9  9  7]
 [ 3  2  3  9]
 [ 7  7  5  1]]


In [70]:
#reshaping array
grid = np.arange(1,10).reshape(3,3)
print(grid)

x = np.array([1,2,3])
print(x.reshape((3,1)))
print(x.reshape(1,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
[[1 2 3]]


In [ ]:
#array concatenation and splitting
#use np.concatenate, np.vstack, and np.hstack
#np.split, np.hsplit, and np.vsplit

In [72]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)
#N split-points, leads to N + 1 subarrays

[1 2 3] [99 99] [3 2 1]


In [74]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [92]:
#Universal Functions Ufuncs
x = np.arange(1,10)
x
print(np.add(x,2))
print(np.subtract(x,2))
print(np.multiply(x,2))
print(np.divide(x,2))
print(np.negative(x))
print(np.floor_divide(x,2))
print(np.power(x,2))
print(np.mod(x,2))

print("now use operators")
print(x+2)
print(x-2)
print(x*2)
print(x/2)
print(x//2)
print(x**2)
print(x%2)

print(x-5)
print(np.abs(x-5))

[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
now use operators
[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[-4 -3 -2 -1  0  1  2  3  4]
[4 3 2 1 0 1 2 3 4]


In [25]:
#Broadcasting operations
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6,7,8,9]).reshape((2,3))
c = np.array([4,5,6]).reshape((3,1))
print(b)
print(a+b)
M =np.ones((3,3))
print(M+a)
b = b.reshape(3,2)
print(b)
print('both arrays dimension different addition:')
print('a is: ',a)
print('c is: ',c)
print(a+c)

[[4 5 6]
 [7 8 9]]
[[ 5  7  9]
 [ 8 10 12]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[4 5]
 [6 7]
 [8 9]]
both arrays dimension different addition:
a is:  [1 2 3]
c is:  [[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [31]:
M = np.ones((2,3))
print(M)
a = np.arange(3)
print(a)
print(M+a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [106]:
#trigonometric functions
#all angles are in radians in trignometric functions
#change angles to degrees and vice-versa using degrees and radians
theta = np.linspace(0,np.pi,3)
print(theta)

print('sin =  {}'.format(np.sin(theta)))
print('cos =  {}'.format(np.cos(theta)))
print('tan =  {}'.format(np.tan(theta)))
print(np.degrees(theta))
y= np.degrees(theta)
x= np.radians(y)
print(x)
x= np.array([-1,0,1])
print(type(x))
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

[0.         1.57079633 3.14159265]
sin =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.  90. 180.]
[0.         1.57079633 3.14159265]
<class 'numpy.ndarray'>
x         =  [-1  0  1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [110]:
#exponentials and logarithms
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))


x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))



x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [136]:
#Aggregates
np.random.seed(0)
x = np.array([1,2,3,4,5,6])
print(x)
print('sum: ',np.sum(x))
print('max: ',np.max(x))
print('min: ',np.min(x))

y = np.random.randint(0,10,(3,3))
print(y)
print(type(y))
print('sum: ',np.sum(y))
print('max: ',np.max(y))
print('min: ',np.min(y))
print('column min: ', np.min(y,axis=0))
print('row max: ', np.max(y,axis=1))

#can also call as 
print('sum: ', y.sum())

print('product: ',np.prod(x))
print('mean: ',np.mean(x))
print('median: ',np.median(x))
print('25th percentile:',np.percentile(x,25))
print('std: ',np.std(x))
print('variance: ',np.var(x))
print('index of min value: ',np.argmin(x))
print('index of max value: ',np.argmax(x))

[1 2 3 4 5 6]
sum:  21
max:  6
min:  1
[[5 0 3]
 [3 7 9]
 [3 5 2]]
<class 'numpy.ndarray'>
sum:  37
max:  9
min:  0
column min:  [3 0 2]
row max:  [5 9 5]
sum:  37
product:  720
mean:  3.5
median:  3.5
rank percentile: 2.25
std:  1.707825127659933
variance:  2.9166666666666665
index of min value:  0
index of max value:  5


In [36]:
np.random.seed(0)
x= np.random.random((10,3))
x_mean = x.mean(0) #take mean across the first dimension
print(x_mean)
x_centered = x- x_mean
#centered matrix should have near zero mean
print(x_centered.mean())


[0.52101579 0.62614181 0.59620338]
5.551115123125783e-17
