In [ ]:
#NUMPY

In [34]:
#Boolean masking
import numpy as np
x = np.array([1,2,3,4,5,6])
print('x<3: ',x<3)
print('x<3: ',np.less(x,3))

print('x>=3: ',x>=3)
print('x!=3: ',x!=3)
print('x=3: ',x==3)

print((2 * x) == (x **2))

print('number of values greater than 1:', np.sum(x>1))
print('number of values between 1 and 5 exclusive:', np.sum((x>1) & (x<5))) #cannot use and
print('number of values not divisible by 3:',np.sum(~(x%3==0))) 
print('number of even values or 1:',np.sum((x==1) | (x%2==0))) #cannot use or 

x<3:  [ True  True False False False False]
x<3:  [ True  True False False False False]
x>=3:  [False False  True  True  True  True]
x!=3:  [ True  True False  True  True  True]
x=3:  [False False  True False False False]
[False  True False False False False]
number of values greater than 1: 5
number of values between 1 and 5 exclusive: 3
number of values not divisible by 3: 4
number of even values or 1: 4


In [24]:
x= np.array([1,2,3,4,5,6])
print('values greater than or equal to 4:', x[x>=4])
print('minimum value greater than 3:',np.min(x[x>3]))

values greater than or equal to 4: [4 5 6]
minimum value greater than 3: 4


In [17]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x)
print('number of values less than 6:', np.count_nonzero(x<6)) #since True is 1
print('number of values less than 6:', np.sum(x<6))
print('number of values less than 6 in each row:', np.sum(x<6, axis=1))
print('any value less than 6:', np.any(x<6))
print('all values less than 10 in a row:', np.any(x<10, axis=1))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
number of values less than 6: 8
number of values less than 6: 8
number of values less than 6 in each row: [4 2 2]
any value less than 6: True
all values less than 10 in a row: [ True  True  True]


In [39]:
print(42 and 1)
print(42 and 0)
print(42 or 0)
print(42 & 0)
print(42 | 0)
#but and/or operators act different than &/| in numpy array
x = np.array([1,2,3,4,5,6])
print((x>3) & (x<6))
print((x>3) and (x<6))

1
0
42
0
42
[False False False  True  True False]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()