In [20]:
#NUMPY Fancy Indexing
import numpy as np
np.random.seed(42)

x = np.random.randint(100, size = (10))
print(x)
ind1 = np.array([1,2,4])
print(x[ind1])
#the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed:
ind2 = np.array([[1,4],[2,5],[3,6]])
print(x[ind2])


[51 92 14 71 60 20 82 86 74 74]
[92 14 60]
[[92 60]
 [14 20]
 [71 82]]


In [38]:
np.random.seed(0)
x= np.random.randint(12, size = (3,4))
print(x)
row = np.array([0,1,2])
col = np.array([3,2,1])
print(x[row,col])
print(x[row[:, np.newaxis],col])
print(x[2,[1,2,3]])
print(x[1:,[1,2,3]])



[[ 5  0  3 11]
 [ 3  7  9  3]
 [ 5  2  4  7]]
[11  9  2]
[[11  3  0]
 [ 3  9  7]
 [ 7  4  2]]
[2 4 7]
[[7 9 3]
 [2 4 7]]


In [43]:

np.random.seed(0)
x = np.arange(10)
print(x)
ind = np.array([3,6,9])
x[ind] = -1
print(x)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -1  4  5 -1  7  8 -1]


In [72]:
#creating a histogram 
np.random.seed(42)
x = np.random.randn(100)

#print(x)
# compute a histogram by hand
bins = np.linspace(-5, 5, 20)
#print(bins)
counts = np.zeros_like(bins)
#print(counts)
# find the appropriate bin for each x
i = np.searchsorted(bins, x)
#print(i)

# add 1 to each of these bins
np.add.at(counts, i, 1)
print(counts)

[ 0.  0.  0.  0.  0.  1.  3.  7.  9. 23. 22. 17. 10.  7.  1.  0.  0.  0.
  0.  0.]


In [85]:
#selection_sort

np.random.seed(1)
x = np.random.randint(100, size =20)
print(x)
print(x.shape[0])
len = x.shape[0]
for i in range(0,len):
    for j in range(i, len):
        if x[i] > x[j]:
            tem = x[i]
            x[i] = x[j]
            x[j] = tem
print(x)

[37 12 72  9 75  5 79 64 16  1 76 71  6 25 50 20 18 84 11 28]
20
[ 1  5  6  9 11 12 16 18 20 25 28 37 50 64 71 72 75 76 79 84]


In [88]:
#selection sort

def selection_sort(x):
    for i in range(x.shape[0]):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

np.random.seed(1)
#x = np.random.randint(100, size =20)
x = np.array([1,5,3,0,2,4])
selection_sort(x)

array([0, 1, 2, 3, 4, 5])

In [102]:
np.random.seed(1)
x = np.random.randint(100, size =20)
print('original array: ',x)
print('sorted array: ',np.sort(x))
print('but original array remains unchanged: ',x)
i = np.argsort(x)
print('index of element in sorted array: ',i)
x.sort()
print('sorted array and original array changes: ',x)


original array:  [37 12 72  9 75  5 79 64 16  1 76 71  6 25 50 20 18 84 11 28]
sorted array:  [ 1  5  6  9 11 12 16 18 20 25 28 37 50 64 71 72 75 76 79 84]
but original array remains unchanged:  [37 12 72  9 75  5 79 64 16  1 76 71  6 25 50 20 18 84 11 28]
index of element in sorted array:  [ 9  5 12  3 18  1  8 16 15 13 19  0 14  7 11  2  4 10  6 17]
sorted array and original array changes:  [ 1  5  6  9 11 12 16 18 20 25 28 37 50 64 71 72 75 76 79 84]


In [104]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)
np.sort(X, axis=0)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])